#include<iostream>
#include<stdlib.h>
#include<time.h>
#include<math.h>
#define A 9

using namespace std;
int x[1000],y[1000];

void myrand(){
	int i,j;
	
	//taking random number between 1-50
	x[0]=time(0)%50;
	while(x[0]==0){
		x[0]=time(0)%50;
	}
	
	for(i=0;i<1000;i++){
		
			// value of A is defined above 
			x[i+1]=(x[i]*A)%50;
	}
}

void chi_test(int arr[]){
	int i,sum=0;
	float chi=0,mean;
	
	for(i=0;i<1000;i++){
		sum+=arr[i];
	}
	
	mean = (float)sum/1000;
	cout<<"mean="<<mean<<endl;
	for(i=0;i<1000;i++){
	chi+=(((float)arr[i]-mean)*((float)arr[i]-mean))/(mean);
	}
	chi=sqrt(chi);
	cout<<chi<<endl;
	
}

int main(){
	int i,j,n;
	//firstly generating using myrand() function
	myrand();
	cout<<"numbers generated by myrand()\n";
	for(i=0;i<1000;i++){
		cout<<x[i]<<" ";
	}
	cout<<endl;
		chi_test(x);
	//generating numbers using rand() library function
	
	srand(time(0));
	cout<<"numbers generated by rand()\n";
	for(i=0;i<1000;i++){
		y[i]=(rand()%(50-1+1)+1);
		cout<<y[i]<<" ";
	}
	cout<<endl;
	
	//performing chi-square test

	chi_test(y);
	
	return 0;
}
